---
title: "Linear Regression and Modeling - Project Rubric"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

<br>

#### IMPORTANT: If the analysis is completed using software other than R or not written up using R Markdown, the project should receive a 0 regardless of its content.

<br>

## Part 1: Data (3 points)

- 2 pts. for correct reasoning for generalizability---Answer should discuss whether 
random sampling was used. 

- 1 pt. for correct reasoning for causality---Answer should discuss whether 
random assignment was used.

## Part 2: Research questions (3 points)

- Should be phrased in a non-causal way (1 pt.)
- Should be well defined / not vague (1 pt.)
- Explains why research is of interest to the author / audience (1 pt.)
    
## Part 3: EDA (10 points)

- 3 pts. for plots
    + Plots should address the research questions (1 pt.)
    + Plots should be constructed correctly (1 pt.)
    + Plots should be formatted well: have a descriptive caption, size not too large, not too small, etc. (1 pt.)

- 3 pts. for summary statistics
    + Summary statistics should address the research questions (1 pt.)
    + Summary statistics should be calculated correctly (1 pt.)
    + Summary statistics should be formatted well: not taking up pages and pages, etc. (1 pt.)
    
- 4 pt.s for narrative
    + Each plot and/or R output should be accompanied by complete sentences describing what is seen (1 pt.)
    + Sentences should interpret the visuals / R output correctly (1 pt.)
    + Sentences should address the research question (2 pts.)
  
## Modeling (20 points)

Develop a multiple linear regression model to predict a numerical variable 
in the dataset. The response variable and the explanatory variables can be 
existing variables in the dataset or new variables you create based on existing 
variables.

- Specify which variables to consider for the full model (1 pt)
- Reasoning for excluding certain variables (2 pts)
- Reasoning for choice of model selection method (2 pts)
- Carrying out the model selection correctly (5 pts)
- Model diagnostics (5 pts)
- Interpretation of model coefficients (5 pts)

## Prediction (5 points)

Pick a movie from 2016 (a new movie that is not in the sample), and do a 
prediction for this movie using the model you developed with the `R`
`predict` function. Quantify the uncertainty around this 
prediction using an appropriate interval.

- Correct prediction (2 pts.)
- Correct quantification of uncertainty around this prediction with a prediction interval (1 pt.)
- Correct interpretation of prediction interval (1 pt.)
- Reference(s) for where the data for this movie originate (1 pt.)

## Conclusion (3 points)

A brief summary of your findings from the previous sections **without** 
repeating your statements from earlier as well as a discussion of what you 
have learned about the data and your research question. Discuss 
any shortcomings of your current study (either due to data collection or 
methodology), and include ideas for possible future research.

- Conclusion not repetitive of earlier statements (1 pt.)
- Cohesive synthesis of findings that address the stated research question (1 pt.)
- Discussion of shortcomings (1 pt.)

## Overall (6 points)

- Uploaded HTML document resulting from the Rmd template: 1 pt.
- Organization: 1 pt.
- Readability of the text: 2 pts.
- Readability of the code: 2 pts.