---
title: "Intro to Data & Probability---Project Rubric"
output: 
  html_document: 
    fig_height: 4
    highlight: pygments
    theme: spacelab
---

<br>

#### IMPORTANT: If the analysis is completed using software other than R or not written up using R Markdown, the project should receive a 0 regardless of its content.

<br>

## Part 1: Data (3 points)

- 2 pts. for correct reasoning for generabizability---Answer should discuss whether 
random sampling was used. 

- 1 pt. for correct reasoning for causality---Answer should discuss whether 
random assignment was used.

## Part 2: Research questions (3 points)

- Should be phrased in a non-causal way (1 pt.)
- Should be well defined / not vague (1 pt.)
- Explains why research is of interest to the author / audience (1 pt.)
    
## Part 3: EDA (10 points)

- 3 pts. for plots
    + Plots should address the research questions (1 pt.)
    + Plots should be constructed correctly (1 pt.)
    + Plots should be formatted well: have a descriptive caption, size not too large, not too small, etc. (1 pt.)

- 3 pts. for summary statistics
    + Summary statistics should address the research questions (1 pt.)
    + Summary statistics should be calculated correctly (1 pt.)
    + Summary statistics should be formatted well: not taking up pages and pages, etc. (1 pt.)
    
- 4 pt.s for narrative
    + Each plot and/or R output should be accompanied by complete sentences describing what is seen (1 pt.)
    + Sentences should interpret the visuals / R output correctly (1 pt.)
    + Sentences should address the research question (2 pts.)
  
## Inference (28 points)

Statistical inference via hypothesis testing and/or confidence interval.

- State hypotheses
- Check conditions
- State the method(s) to be used
- Perform inference
- Interpret results
- If applicable, state whether results from various methods agree

It is your responsibility to figure out the appropriate methodology. What techniques you use to conduct inference will depend on the the type of data you are using and the underlying distriubtion of your test statistic. Conduct at least one hypothesis test. Report the p-value associated with your test as well as your statistical and English conclusion. If you are comparing two means, two medians, or two proportions, compute a confidence interval for the parameters of interest. If you are working with categorical variables with more than two levels, you will need to use methods such as ANOVA or chi-square tests for which there are no associated confidence intervals.  If your data fails some conditions and you cannot use a theoretical method, you should use an appropriate simulation-based method.

1. If you can use both theoretical and simulation-based methods, do so. 

2. If you can do both a hypothesis test and a confidence interval do both and comment on the results. 

3. It is essential to make sure the method you are using is appropriate for the data and the research question you are trying to answer.


- Hypotheses stated clearly and match research question (4 pts.)
- Conditions checked in context of data (4 pts.)
- Appropriate methods stated and described (4 pts.)
- Correct code and output (6 pts.)
- Correct interpretations and conclusions (7 pts.)
- Reasoning for why CI is/is not included (3 pts.)

  
## Overall (6 points)

- Uploaded HTML document resulting from the Rmd template: 1 pt.
- Organization: 1 pt.
- Readability of the text: 2 pts.
- Readability of the code: 2 pts.