---
title: "Project Information"
output: html_document
---

Identify research questions using the Behavioral Risk Factor Surveillance System (BRFSS) dataset.

All analyses must be completed using the R programming language via RStudio, and the write up must be an R Markdown document. To help you get started, a template Rmd file (`intro_data_prob_project.Rmd`) is provided. 


## Files

Data - 

`brfss2013.RData`

Codebook - Review this file to find out what each column in the data represents.

`brfss_codebook.html`

Rmd template - Use this template to write up your project. 

`Project1Template.Rmd`

Assessment rubric - Please review the assessment rubric before starting your project.

`Project1Rubric.html`

## Instructions

Your project will consist of 3 parts:

1. Data: (3 points) Describe how the observations in the sample are collected and the implications of this data collection method on the scope of inference (generalizability / causality). Note that you will need to look into the BRFSS documentation to answer this question. See http://www.cdc.gov/brfss/ as well as the "More information on the data" section below.

2. Research questions: (11 points) Develop three research questions you want to answer using the `brfss2013` data. Phrase your research questions in a fashion that matches the scope of inference your data permits. Make sure at least two of your questions involve at least three variables. You are welcome to create new variables based on existing ones. With each question, include a brief discussion (1-2 sentences) explaining why this question is of interest to you and/or your audience.

3. EDA: (30 points) Perform exploratory data analysis (EDA) that addresses each of your three research questions. Your EDA should report appropriate numerical summaries and use appropriate graphs. R output, graphs, and tables should be accompanied by a brief interpretation.  All figures and tables should have captions.

In addition to these parts, there are 6 points allocated to format, to overall organization, and to the readability of your project. There are a total of 50 points. 


## More information on the data

The Behavioral Risk Factor Surveillance System (BRFSS) is a collaborative project between all of the states in the United States (US) and participating US territories and the Centers for Disease Control and Prevention (CDC). The BRFSS is administered and supported by CDC's Population Health Surveillance Branch, under the Division of Population Health at the National Center for Chronic Disease Prevention and Health Promotion. BRFSS is an ongoing surveillance system designed to measure behavioral risk factors for the non-institutionalized adult population (18 years of age and older) residing in the US. The BRFSS was initiated in 1984, with 15 states collecting surveillance data on risk behaviors through monthly telephone interviews. Over time, the number of states participating in the survey increased; by 2001, 50 states, the District of Columbia, Puerto Rico, Guam, and the US Virgin Islands were participating in the BRFSS. Today, all 50 states, the District of Columbia, Puerto Rico, and Guam collect data annually and American Samoa, Federated States of Micronesia, and Palau collect survey data over a limited point- in-time (usually one to three months). In this document, the term “state” is used to refer to all areas participating in BRFSS, including the District of Columbia, Guam, and the Commonwealth of Puerto Rico.

The BRFSS objective is to collect uniform, state-specific data on preventive health practices and risk behaviors that are linked to chronic diseases, injuries, and preventable infectious diseases that affect the adult population. Factors assessed by the BRFSS in 2013 include tobacco use, HIV/AIDS knowledge and prevention, exercise, immunization, health status, healthy days — health-related quality of life, health care access, inadequate sleep, hypertension awareness, cholesterol awareness, chronic health conditions, alcohol consumption, fruits and vegetables consumption, arthritis burden, and seatbelt use. Since 2011, BRFSS conducts both landline telephone- and cellular telephone-based surveys. In conducting the BRFSS landline telephone survey, interviewers collect data from a randomly selected adult in a household. In conducting the cellular telephone version of the BRFSS questionnaire, interviewers collect data from an adult who participates by using a cellular telephone and resides in a private residence or college housing.

Health characteristics estimated from the BRFSS pertain to the non-institutionalized adult population, aged 18 years or older, who reside in the US. In 2013, additional question sets were included as optional modules to provide a measure for several childhood health and wellness indicators, including asthma prevalence for people aged 17 years or younger.


Source: [Duke University Data and Visualization Services](http://guides.library.duke.edu/c.php?g=289704&p=1930833)